# Generated by Django 5.2.8 on 2026-01-11 06:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DTTDCTourCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=350, unique=True)),
                ('category_image', models.ImageField(upload_to='tour_categories/%Y/%m/')),
            ],
            options={
                'verbose_name': 'tour category',
                'verbose_name_plural': 'tour categories',
                'db_table': 'dttdc_tour_category',
            },
        ),
        migrations.CreateModel(
            name='DTTDCTour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tour_name', models.CharField(max_length=200)),
                ('tour_image', models.ImageField(blank=True, null=True, upload_to='tours/%Y/%m/')),
                ('schedule', models.TextField(blank=True, null=True)),
                ('timing', models.CharField(blank=True, max_length=445, null=True)),
                ('places_covered', models.TextField(blank=True, null=True)),
                ('fare_adult', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fare_child', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tour_duration', models.CharField(blank=True, max_length=300, null=True)),
                ('total_days', models.PositiveIntegerField(blank=True, null=True)),
                ('departure_dated', models.TextField(blank=True, null=True)),
                ('tour_details', models.TextField(blank=True, null=True)),
                ('tour_status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Not Active')], default='active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('extra_details', models.TextField(blank=True, null=True)),
                ('tour_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tours', to='ebooking.dttdctourcategory')),
            ],
            options={
                'verbose_name': 'tour',
                'verbose_name_plural': 'tours',
                'db_table': 'dttdc_tour',
            },
        ),
        migrations.CreateModel(
            name='DTTDCUserDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tour_journey_date', models.DateField()),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=15)),
                ('passport', models.CharField(blank=True, max_length=20, null=True)),
                ('number_of_adults', models.PositiveSmallIntegerField(default=1)),
                ('number_of_child', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dttdc_tour', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='ebooking.dttdctour')),
            ],
            options={
                'db_table': 'dttdc_user_details',
            },
        ),
        migrations.AddIndex(
            model_name='dttdctour',
            index=models.Index(fields=['tour_category'], name='idx_dttdc_tour_tour_category'),
        ),
        migrations.AddIndex(
            model_name='dttdcuserdetails',
            index=models.Index(fields=['email'], name='dttdc_user__email_cbe2f4_idx'),
        ),
        migrations.AddIndex(
            model_name='dttdcuserdetails',
            index=models.Index(fields=['phone_number'], name='dttdc_user__phone_n_253e4e_idx'),
        ),
        migrations.AddIndex(
            model_name='dttdcuserdetails',
            index=models.Index(fields=['tour_journey_date'], name='dttdc_user__tour_jo_156ce4_idx'),
        ),
    ]
