# Generated by Django 5.2.8 on 2025-11-21 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DTTDCTourCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=350, unique=True)),
                ('category_image', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'tour category',
                'verbose_name_plural': 'tour categories',
                'db_table': 'dttdc_tour_category',
            },
        ),
        migrations.CreateModel(
            name='DTTDCTour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tour_name', models.CharField(max_length=200)),
                ('tour_image', models.TextField(blank=True, null=True)),
                ('schedule', models.TextField(blank=True, null=True)),
                ('timing', models.CharField(blank=True, max_length=445, null=True)),
                ('places_covered', models.TextField(blank=True, null=True)),
                ('fare_adult', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fare_child', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tour_duration', models.CharField(blank=True, max_length=300, null=True)),
                ('total_days', models.PositiveIntegerField(blank=True, null=True)),
                ('departure_dated', models.TextField(blank=True, null=True)),
                ('tour_details', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tour_status', models.CharField(blank=True, max_length=45, null=True)),
                ('extra_details', models.TextField(blank=True, null=True)),
                ('tour_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tours', to='ebooking.dttdctourcategory')),
            ],
            options={
                'db_table': 'dttdc_tour',
                'indexes': [models.Index(fields=['tour_category'], name='idx_dttdc_tour_tour_category')],
            },
        ),
    ]
