# Generated by Django 5.2.8 on 2026-04-30 05:18

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import ebooking.validators
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DTTDCTour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tour_name', models.CharField(max_length=200)),
                ('tour_image', models.ImageField(blank=True, null=True, upload_to='tours/%Y/%m/')),
                ('schedule', models.TextField(blank=True, null=True)),
                ('timing', models.CharField(blank=True, max_length=445, null=True)),
                ('places_covered', models.TextField(blank=True, null=True)),
                ('fare_adult', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fare_child', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tour_duration', models.CharField(blank=True, max_length=300, null=True)),
                ('total_days', models.PositiveIntegerField(blank=True, null=True)),
                ('departure_dated', models.TextField(blank=True, null=True)),
                ('tour_details', models.TextField(blank=True, null=True)),
                ('tour_status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Not Active')], default='active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('extra_details', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'tour',
                'verbose_name_plural': 'tours',
                'db_table': 'dttdc_tour',
            },
        ),
        migrations.CreateModel(
            name='DTTDCTourCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=350, unique=True)),
                ('category_image', models.ImageField(upload_to='tour_categories/%Y/%m/')),
            ],
            options={
                'verbose_name': 'tour category',
                'verbose_name_plural': 'tour categories',
                'db_table': 'dttdc_tour_category',
            },
        ),
        migrations.CreateModel(
            name='DTTDCTraveller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('age', models.PositiveSmallIntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('passport', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=40)),
                ('phone', models.CharField(max_length=20)),
                ('feedback_date', models.DateTimeField(auto_now_add=True)),
                ('comment', models.CharField(max_length=2000)),
            ],
            options={
                'db_table': 'feedback',
                'ordering': ['-feedback_date'],
            },
        ),
        migrations.CreateModel(
            name='DTTDCTourBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pnr_number', models.CharField(max_length=20, unique=True)),
                ('ticket_number', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('invoice_number', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('booking_status', models.CharField(choices=[('initiated', 'Initiated'), ('paid', 'Paid'), ('partial_cancelled', 'Partial Cancelled'), ('cancelled', 'Cancelled'), ('completed', 'Completed'), ('payment_pending', 'Payment Pending'), ('payment_failed', 'Payment Failed'), ('payment_timeout', 'Payment Timeout')], max_length=20)),
                ('booking_date', models.DateTimeField(auto_now_add=True)),
                ('total_fare', models.DecimalField(decimal_places=2, max_digits=10)),
                ('number_of_passengers', models.PositiveSmallIntegerField()),
                ('dttdc_tour', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ebooking.dttdctour')),
            ],
        ),
        migrations.CreateModel(
            name='DTTDCTourCancellation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cancellation_type', models.CharField(choices=[('full', 'Full'), ('partial', 'Partial')], max_length=45)),
                ('cancellation_date', models.DateTimeField(auto_now_add=True)),
                ('cancellation_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=45)),
                ('cancellation_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('admin_approval_date', models.DateTimeField(blank=True, null=True)),
                ('tour_booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cancellation', to='ebooking.dttdctourbooking')),
            ],
        ),
        migrations.AddField(
            model_name='dttdctour',
            name='tour_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tours', to='ebooking.dttdctourcategory'),
        ),
        migrations.CreateModel(
            name='DTTDCTourPaymentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isConsentPayment', models.CharField(blank=True, max_length=45, null=True)),
                ('mihpayid', models.CharField(blank=True, max_length=45, null=True)),
                ('mode', models.CharField(blank=True, max_length=45, null=True)),
                ('status', models.CharField(max_length=45)),
                ('unmappedstatus', models.CharField(blank=True, max_length=45, null=True)),
                ('key1', models.CharField(blank=True, max_length=45, null=True)),
                ('txnid', models.CharField(max_length=45, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('addedon', models.DateTimeField()),
                ('firstname', models.CharField(max_length=45)),
                ('lastname', models.CharField(blank=True, max_length=45, null=True)),
                ('email', models.EmailField(max_length=45)),
                ('phone', models.CharField(max_length=45)),
                ('address1', models.CharField(max_length=255)),
                ('address2', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(max_length=45)),
                ('state', models.CharField(max_length=45)),
                ('country', models.CharField(max_length=45)),
                ('zipcode', models.CharField(max_length=45)),
                ('productinfo', models.CharField(max_length=255)),
                ('udf1', models.CharField(blank=True, max_length=450, null=True)),
                ('udf2', models.CharField(blank=True, max_length=450, null=True)),
                ('udf3', models.CharField(blank=True, max_length=450, null=True)),
                ('udf4', models.CharField(blank=True, max_length=450, null=True)),
                ('udf5', models.CharField(blank=True, max_length=450, null=True)),
                ('udf6', models.CharField(blank=True, max_length=450, null=True)),
                ('udf7', models.CharField(blank=True, max_length=450, null=True)),
                ('udf8', models.CharField(blank=True, max_length=450, null=True)),
                ('udf9', models.CharField(blank=True, max_length=450, null=True)),
                ('udf10', models.CharField(blank=True, max_length=450, null=True)),
                ('hash', models.CharField(max_length=4000)),
                ('PG_TYPE', models.CharField(blank=True, max_length=45, null=True)),
                ('encryptedPaymentId', models.CharField(blank=True, max_length=450, null=True)),
                ('bank_ref_num', models.CharField(blank=True, max_length=45, null=True)),
                ('bankcode', models.CharField(blank=True, max_length=45, null=True)),
                ('name_on_card', models.CharField(blank=True, max_length=45, null=True)),
                ('cardnum', models.CharField(blank=True, max_length=45, null=True)),
                ('cardhash', models.CharField(blank=True, max_length=450, null=True)),
                ('amount_split', models.CharField(blank=True, max_length=45, null=True)),
                ('discount', models.CharField(blank=True, max_length=45, null=True)),
                ('net_amount_debit', models.CharField(blank=True, max_length=45, null=True)),
                ('error', models.CharField(blank=True, max_length=45, null=True)),
                ('error_Message', models.CharField(blank=True, max_length=500, null=True)),
                ('payuMoneyId', models.CharField(blank=True, max_length=45, null=True)),
                ('giftCardIssued', models.CharField(blank=True, max_length=45, null=True)),
                ('user_ip', models.CharField(blank=True, max_length=30, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='payment', to='ebooking.dttdctourbooking')),
            ],
            options={
                'db_table': 'dttdc_tour_payment_details',
            },
        ),
        migrations.CreateModel(
            name='DTTDCCancellationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cancellation_type', models.CharField(choices=[('partial', 'Partial'), ('full', 'Full')], max_length=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cancellation_history', to='ebooking.dttdctourbooking')),
                ('traveller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancellation_history', to='ebooking.dttdctraveller')),
            ],
        ),
        migrations.CreateModel(
            name='DTTDCTravellerBookingMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_status', models.CharField(blank=True, choices=[('booked', 'Booked'), ('cancelled', 'Cancelled'), ('travelled', 'Travelled'), ('no_show', 'No Show'), ('refunded', 'Refunded')], max_length=20, null=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passenger_map', to='ebooking.dttdctourbooking')),
                ('traveller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='ebooking.dttdctraveller')),
            ],
        ),
        migrations.CreateModel(
            name='DTTDCUserDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tour_journey_date', models.DateField(validators=[ebooking.validators.journey_date_validator])),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Enter a valid 6-digit PIN code.', regex='^\\d{6}$')])),
                ('passport', models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Passport number must be 6–12 alphanumeric characters.', regex='^[A-Z0-9]{6,12}$')])),
                ('number_of_adults', models.PositiveSmallIntegerField(default=1)),
                ('number_of_child', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_details', to='ebooking.dttdctourbooking')),
            ],
        ),
        migrations.AddField(
            model_name='dttdctraveller',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travellers', to='ebooking.dttdcuserdetails'),
        ),
        migrations.CreateModel(
            name='DTTDCTourAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_date', models.DateField()),
                ('total_seats', models.PositiveIntegerField()),
                ('available_seats', models.PositiveIntegerField()),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='ebooking.dttdctour')),
            ],
            options={
                'db_table': 'dttdc_tour_availability',
                'ordering': ['available_date'],
                'unique_together': {('tour', 'available_date')},
            },
        ),
        migrations.AddIndex(
            model_name='dttdctour',
            index=models.Index(fields=['tour_category'], name='idx_dttdc_tour_tour_category'),
        ),
        migrations.AddIndex(
            model_name='dttdctourpaymentdetails',
            index=models.Index(fields=['txnid'], name='dttdc_tour__txnid_bc2de7_idx'),
        ),
        migrations.AddIndex(
            model_name='dttdctourpaymentdetails',
            index=models.Index(fields=['mihpayid'], name='dttdc_tour__mihpayi_a1fd72_idx'),
        ),
        migrations.AddIndex(
            model_name='dttdctourpaymentdetails',
            index=models.Index(fields=['status'], name='dttdc_tour__status_698286_idx'),
        ),
        migrations.AddIndex(
            model_name='dttdctourpaymentdetails',
            index=models.Index(fields=['email'], name='dttdc_tour__email_a74e09_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dttdccancellationhistory',
            unique_together={('booking', 'traveller')},
        ),
        migrations.AlterUniqueTogether(
            name='dttdctravellerbookingmap',
            unique_together={('booking', 'traveller')},
        ),
    ]
