# Generated by Django 5.2.8 on 2025-11-26 05:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebooking', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dttdctour',
            options={'verbose_name': 'tour', 'verbose_name_plural': 'tours'},
        ),
        migrations.CreateModel(
            name='DTTDCUserDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tour_booking_date', models.DateField()),
                ('email', models.EmailField(max_length=45, unique=True)),
                ('name', models.CharField(max_length=45)),
                ('address', models.TextField(max_length=500)),
                ('city', models.CharField(max_length=45)),
                ('pincode', models.CharField(max_length=10)),
                ('phone_number', models.CharField(max_length=15)),
                ('state', models.CharField(max_length=45)),
                ('country', models.CharField(max_length=45)),
                ('passport', models.CharField(blank=True, max_length=20, null=True)),
                ('number_of_adults', models.PositiveIntegerField()),
                ('number_of_child', models.PositiveIntegerField(blank=True, null=True)),
                ('tour_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_details', to='ebooking.dttdctour')),
            ],
            options={
                'db_table': 'dttdc_user_details',
                'indexes': [models.Index(fields=['tour_id'], name='idx_dttdc_user_deails_tour_id')],
            },
        ),
    ]
