# Generated by Django 5.2.8 on 2026-01-11 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebooking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DTTDCTourBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pnr_number', models.CharField(max_length=20, unique=True)),
                ('ticket_number', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('invoice_number', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('booking_status', models.CharField(choices=[('initiated', 'Initiated'), ('paid', 'Paid'), ('partial_cancelled', 'Partial Cancelled'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], max_length=20)),
                ('booking_date', models.DateTimeField(auto_now_add=True)),
                ('total_fare', models.DecimalField(decimal_places=2, max_digits=10)),
                ('number_of_passengers', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DTTDCTourPaymentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isConsentPayment', models.CharField(blank=True, max_length=45, null=True)),
                ('mihpayid', models.CharField(blank=True, max_length=45, null=True)),
                ('mode', models.CharField(blank=True, max_length=45, null=True)),
                ('status', models.CharField(max_length=45)),
                ('unmappedstatus', models.CharField(blank=True, max_length=45, null=True)),
                ('key1', models.CharField(blank=True, max_length=45, null=True)),
                ('txnid', models.CharField(max_length=45, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('addedon', models.DateTimeField()),
                ('firstname', models.CharField(max_length=45)),
                ('lastname', models.CharField(blank=True, max_length=45, null=True)),
                ('email', models.EmailField(max_length=45)),
                ('phone', models.CharField(max_length=45)),
                ('address1', models.CharField(max_length=255)),
                ('address2', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(max_length=45)),
                ('state', models.CharField(max_length=45)),
                ('country', models.CharField(max_length=45)),
                ('zipcode', models.CharField(max_length=45)),
                ('productinfo', models.CharField(max_length=255)),
                ('udf1', models.CharField(blank=True, max_length=450, null=True)),
                ('udf2', models.CharField(blank=True, max_length=450, null=True)),
                ('udf3', models.CharField(blank=True, max_length=450, null=True)),
                ('udf4', models.CharField(blank=True, max_length=450, null=True)),
                ('udf5', models.CharField(blank=True, max_length=450, null=True)),
                ('udf6', models.CharField(blank=True, max_length=450, null=True)),
                ('udf7', models.CharField(blank=True, max_length=450, null=True)),
                ('udf8', models.CharField(blank=True, max_length=450, null=True)),
                ('udf9', models.CharField(blank=True, max_length=450, null=True)),
                ('udf10', models.CharField(blank=True, max_length=450, null=True)),
                ('hash', models.CharField(max_length=4000)),
                ('PG_TYPE', models.CharField(blank=True, max_length=45, null=True)),
                ('encryptedPaymentId', models.CharField(blank=True, max_length=450, null=True)),
                ('bank_ref_num', models.CharField(blank=True, max_length=45, null=True)),
                ('bankcode', models.CharField(blank=True, max_length=45, null=True)),
                ('name_on_card', models.CharField(blank=True, max_length=45, null=True)),
                ('cardnum', models.CharField(blank=True, max_length=45, null=True)),
                ('cardhash', models.CharField(blank=True, max_length=450, null=True)),
                ('amount_split', models.CharField(blank=True, max_length=45, null=True)),
                ('discount', models.CharField(blank=True, max_length=45, null=True)),
                ('net_amount_debit', models.CharField(blank=True, max_length=45, null=True)),
                ('error', models.CharField(blank=True, max_length=45, null=True)),
                ('error_Message', models.CharField(blank=True, max_length=500, null=True)),
                ('payuMoneyId', models.CharField(blank=True, max_length=45, null=True)),
                ('giftCardIssued', models.CharField(blank=True, max_length=45, null=True)),
                ('user_ip', models.CharField(blank=True, max_length=30, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'dttdc_tour_payment_details',
            },
        ),
        migrations.CreateModel(
            name='DTTDCTraveller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passenger_id', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('age', models.PositiveSmallIntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('passport', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DTTDCTravellerBookingMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_status', models.CharField(choices=[('booked', 'Booked'), ('cancelled', 'Cancelled'), ('travelled', 'Travelled'), ('no_show', 'No Show'), ('refunded', 'Refunded')], max_length=20)),
            ],
        ),
        migrations.RemoveIndex(
            model_name='dttdcuserdetails',
            name='dttdc_user__email_cbe2f4_idx',
        ),
        migrations.RemoveIndex(
            model_name='dttdcuserdetails',
            name='dttdc_user__phone_n_253e4e_idx',
        ),
        migrations.RemoveIndex(
            model_name='dttdcuserdetails',
            name='dttdc_user__tour_jo_156ce4_idx',
        ),
        migrations.RemoveField(
            model_name='dttdcuserdetails',
            name='dttdc_tour',
        ),
        migrations.AlterModelTable(
            name='dttdcuserdetails',
            table=None,
        ),
        migrations.AddField(
            model_name='dttdctourbooking',
            name='dttdc_tour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ebooking.dttdctour'),
        ),
        migrations.AddField(
            model_name='dttdcuserdetails',
            name='booking',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_details', to='ebooking.dttdctourbooking'),
        ),
        migrations.AddField(
            model_name='dttdctourpaymentdetails',
            name='booking',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='payment', to='ebooking.dttdctourbooking'),
        ),
        migrations.AddField(
            model_name='dttdctraveller',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travellers', to='ebooking.dttdcuserdetails'),
        ),
        migrations.AddField(
            model_name='dttdctravellerbookingmap',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passenger_map', to='ebooking.dttdctourbooking'),
        ),
        migrations.AddField(
            model_name='dttdctravellerbookingmap',
            name='traveller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='ebooking.dttdctraveller'),
        ),
        migrations.AddIndex(
            model_name='dttdctourpaymentdetails',
            index=models.Index(fields=['txnid'], name='dttdc_tour__txnid_bc2de7_idx'),
        ),
        migrations.AddIndex(
            model_name='dttdctourpaymentdetails',
            index=models.Index(fields=['mihpayid'], name='dttdc_tour__mihpayi_a1fd72_idx'),
        ),
        migrations.AddIndex(
            model_name='dttdctourpaymentdetails',
            index=models.Index(fields=['status'], name='dttdc_tour__status_698286_idx'),
        ),
        migrations.AddIndex(
            model_name='dttdctourpaymentdetails',
            index=models.Index(fields=['email'], name='dttdc_tour__email_a74e09_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dttdctravellerbookingmap',
            unique_together={('booking', 'traveller')},
        ),
    ]
