# Generated by Django 4.2.7 on 2026-01-21 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ebooking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DTTDCTourAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_date', models.DateField()),
                ('total_seats', models.PositiveIntegerField()),
                ('available_seats', models.PositiveIntegerField()),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='ebooking.dttdctour')),
            ],
            options={
                'db_table': 'dttdc_tour_availability',
                'ordering': ['available_date'],
                'unique_together': {('tour', 'available_date')},
            },
        ),
    ]
