# Generated by Django 5.2.8 on 2025-12-11 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebooking', '0002_alter_dttdctour_options_dttdcuserdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dttdctourcategory',
            name='category_image',
            field=models.ImageField(blank=True, null=True, upload_to='tour_categories/%Y/%m/'),
        ),
    ]
