# Generated by Django 4.2.7 on 2026-01-24 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ebooking', '0002_dttdctouravailability'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dttdctraveller',
            name='passenger_id',
        ),
    ]
