# Generated by Django 4.2.7 on 2026-01-28 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebooking', '0003_remove_dttdctraveller_passenger_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dttdctravellerbookingmap',
            name='booking_status',
            field=models.CharField(blank=True, choices=[('booked', 'Booked'), ('cancelled', 'Cancelled'), ('travelled', 'Travelled'), ('no_show', 'No Show'), ('refunded', 'Refunded')], max_length=20, null=True),
        ),
    ]
