# Generated by Django 5.2.8 on 2025-12-11 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebooking', '0003_alter_dttdctourcategory_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dttdctourcategory',
            name='category_image',
            field=models.ImageField(default=None, upload_to='tour_categories/%Y/%m/'),
            preserve_default=False,
        ),
    ]
