# Generated by Django 5.2.9 on 2025-12-15 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebooking', '0004_alter_dttdctourcategory_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dttdctour',
            name='tour_image',
            field=models.ImageField(blank=True, null=True, upload_to='tours/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='dttdctour',
            name='tour_status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Not Active')], default='active', max_length=10),
        ),
    ]
