# Generated by Django 5.2.8 on 2026-01-29 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebooking', '0004_alter_dttdctravellerbookingmap_booking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dttdctourbooking',
            name='booking_status',
            field=models.CharField(choices=[('initiated', 'Initiated'), ('paid', 'Paid'), ('partial_cancelled', 'Partial Cancelled'), ('cancelled', 'Cancelled'), ('completed', 'Completed'), ('payment_pending', 'Payment Pending'), ('payment_failed', 'Payment Failed'), ('payment_timeout', 'Payment Timeout')], max_length=20),
        ),
    ]
