# Generated by Django 4.2.7 on 2026-02-17 09:02

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import ebooking.validators
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('ebooking', '0005_alter_dttdctourbooking_booking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dttdcuserdetails',
            name='passport',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Passport number must be 6–12 alphanumeric characters.', regex='^[A-Z0-9]{6,12}$')]),
        ),
        migrations.AlterField(
            model_name='dttdcuserdetails',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
        migrations.AlterField(
            model_name='dttdcuserdetails',
            name='pincode',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Enter a valid 6-digit PIN code.', regex='^\\d{6}$')]),
        ),
        migrations.AlterField(
            model_name='dttdcuserdetails',
            name='tour_journey_date',
            field=models.DateField(validators=[ebooking.validators.journey_date_validator]),
        ),
        migrations.CreateModel(
            name='DTTDCTourCancellation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cancellation_type', models.CharField(choices=[('full', 'Full'), ('partial', 'Partial')], max_length=45)),
                ('cancellation_date', models.DateTimeField(auto_now_add=True)),
                ('cancellation_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=45)),
                ('admin_approval_date', models.DateTimeField(blank=True, null=True)),
                ('tour_booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cancellation', to='ebooking.dttdctourbooking')),
            ],
        ),
    ]
