# Generated by Django 6.0.2 on 2026-02-04 06:27

import django.core.validators
import ebooking.validators
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebooking', '0005_alter_dttdctourbooking_booking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dttdcuserdetails',
            name='passport',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Passport number must be 6–12 alphanumeric characters.', regex='^[A-Z0-9]{6,12}$')]),
        ),
        migrations.AlterField(
            model_name='dttdcuserdetails',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
        migrations.AlterField(
            model_name='dttdcuserdetails',
            name='pincode',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Enter a valid 6-digit PIN code.', regex='^\\d{6}$')]),
        ),
        migrations.AlterField(
            model_name='dttdcuserdetails',
            name='tour_journey_date',
            field=models.DateField(validators=[ebooking.validators.journey_date_validator]),
        ),
    ]
