# Generated by Django 5.2.9 on 2025-12-16 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebooking', '0005_alter_dttdctour_tour_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dttdctour',
            name='extra_details',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
