# Generated by Django 5.2.9 on 2025-12-16 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebooking', '0006_alter_dttdctour_extra_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dttdctour',
            name='extra_details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
