# Generated by Django 4.2.7 on 2026-03-17 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebooking', '0006_alter_dttdcuserdetails_passport_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dttdctourcancellation',
            name='passengers',
            field=models.ManyToManyField(to='ebooking.dttdctraveller'),
        ),
    ]
