# Generated by Django 4.2.7 on 2026-03-18 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ebooking', '0007_dttdctourcancellation_passengers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dttdctourcancellation',
            name='passengers',
        ),
    ]
