# Generated by Django 5.2.12 on 2026-03-18 09:59

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebooking', '0008_remove_dttdctourcancellation_passengers'),
    ]

    operations = [
        migrations.CreateModel(
            name='DTTDCCancellationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cancellation_type', models.CharField(choices=[('partial', 'Partial'), ('full', 'Full')], max_length=10)),
                ('cancellation_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cancellation_history', to='ebooking.dttdctourbooking')),
                ('traveller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancellation_history', to='ebooking.dttdctraveller')),
            ],
        ),
    ]
