# Generated by Django 5.2.12 on 2026-03-19 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ebooking', '0009_dttdccancellationhistory'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dttdccancellationhistory',
            unique_together={('booking', 'traveller')},
        ),
    ]
