# Generated by Django 5.2.12 on 2026-03-25 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ebooking', '0010_alter_dttdccancellationhistory_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dttdccancellationhistory',
            name='cancellation_amount',
        ),
    ]
