# Generated by Django 5.2.12 on 2026-03-25 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebooking', '0011_remove_dttdccancellationhistory_cancellation_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='dttdctourcancellation',
            name='cancellation_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
