# Generated by Django 4.2.7 on 2026-04-06 08:42

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarBookingBookingDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('journeyDate', models.DateField()),
                ('bookingStatus', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('fullName', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('phoneNumber', models.CharField(max_length=255)),
                ('passportNumber', models.CharField(max_length=255)),
                ('pickUpPlace', models.CharField(max_length=255)),
                ('pickUpTime', models.TimeField()),
                ('totalFare', models.FloatField()),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CarBookingCancellation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cancellationStatus', models.CharField(max_length=255)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('bookingDetails', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carbooking.carbookingbookingdetails')),
            ],
        ),
        migrations.CreateModel(
            name='CarBookingCaptcha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('captchaValue', models.CharField(max_length=255)),
                ('captchaToken', models.CharField(max_length=255)),
                ('attempts', models.IntegerField()),
                ('validateStatus', models.BooleanField()),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CarBookingPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('packageName', models.CharField(max_length=255)),
                ('status', models.BooleanField(default=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CarBookingPackageCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('packageCategoryName', models.CharField(max_length=255)),
                ('status', models.BooleanField(default=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CarBookingVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicleName', models.CharField(max_length=255)),
                ('vehicleImage', models.CharField(max_length=255)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('phoneNumber', models.CharField(max_length=255)),
                ('comment', models.TextField()),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('name', models.CharField(max_length=255)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('OTP', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('verified', models.BooleanField()),
                ('attempts', models.IntegerField()),
                ('OTPSentCount', models.IntegerField()),
                ('generationTime', models.DateTimeField()),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('active', models.BooleanField()),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CarBookingVehicleDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicleCapacity', models.CharField(max_length=255)),
                ('tourDescription', models.TextField()),
                ('baseFare', models.FloatField()),
                ('GST', models.FloatField()),
                ('extraPerKM', models.FloatField()),
                ('extraPerHour', models.FloatField()),
                ('perNightCharge', models.FloatField()),
                ('status', models.BooleanField(default=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carbooking.carbookingpackage')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carbooking.carbookingvehicle')),
            ],
        ),
        migrations.CreateModel(
            name='CarBookingTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txnid', models.CharField(max_length=255)),
                ('amount', models.FloatField()),
                ('paymentStatus', models.CharField(max_length=255)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('bookingDetails', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carbooking.carbookingbookingdetails')),
            ],
        ),
        migrations.CreateModel(
            name='CarBookingTicketDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pnrNumber', models.CharField(max_length=255)),
                ('invoiceNumber', models.CharField(max_length=255)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('bookingDetails', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carbooking.carbookingbookingdetails')),
            ],
        ),
        migrations.CreateModel(
            name='CarBookingRefund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refundAmount', models.FloatField()),
                ('refundStatus', models.CharField(max_length=255)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('cancellation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carbooking.carbookingcancellation')),
            ],
        ),
        migrations.CreateModel(
            name='CarBookingPaymentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paymentResponse', models.TextField()),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('transactionData', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carbooking.carbookingtransaction')),
            ],
        ),
        migrations.AddField(
            model_name='carbookingpackage',
            name='carPackageCategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carbooking.carbookingpackagecategory'),
        ),
        migrations.AddField(
            model_name='carbookingbookingdetails',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='carbooking.carbookingvehicle'),
        ),
        migrations.CreateModel(
            name='CarBookingAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalSeats', models.IntegerField()),
                ('availableSeats', models.IntegerField()),
                ('availableDate', models.DateField()),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('vehicleDetails', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carbooking.carbookingvehicledetails')),
            ],
        ),
    ]
