# Generated by Django 5.2.12 on 2026-05-06 05:53

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarBookingBookingDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('journeyDate', models.DateField()),
                ('bookingStatus', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('fullName', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('pincode', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Enter a valid 6-digit PIN code.', regex='^\\d{6}$')])),
                ('phoneNumber', models.CharField(max_length=255)),
                ('passportNumber', models.CharField(max_length=255)),
                ('pickUpPlace', models.CharField(max_length=255)),
                ('pickUpTime', models.TimeField()),
                ('totalFare', models.FloatField()),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CarBookingCaptcha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('captchaValue', models.CharField(max_length=255)),
                ('captchaToken', models.CharField(max_length=255)),
                ('attempts', models.IntegerField()),
                ('validateStatus', models.BooleanField()),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CarBookingPackageCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('packageCategoryName', models.CharField(max_length=255)),
                ('status', models.BooleanField(default=True)),
                ('categoryImage', models.ImageField(blank=True, null=True, upload_to='package_categories/%Y/%m/')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CarBookingVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicleName', models.CharField(max_length=255)),
                ('vehicleImage', models.ImageField(blank=True, null=True, upload_to='vehicles/%Y/%m/')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('phoneNumber', models.CharField(max_length=255)),
                ('comment', models.TextField()),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('name', models.CharField(max_length=255)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('OTP', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('verified', models.BooleanField()),
                ('attempts', models.IntegerField()),
                ('OTPSentCount', models.IntegerField()),
                ('generationTime', models.DateTimeField()),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('active', models.BooleanField()),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CarBookingCancellation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cancellationStatus', models.CharField(max_length=255)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('bookingDetails', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carbooking.carbookingbookingdetails')),
            ],
        ),
        migrations.CreateModel(
            name='CarBookingPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('packageName', models.CharField(max_length=255)),
                ('status', models.BooleanField(default=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('carPackageCategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carbooking.carbookingpackagecategory')),
            ],
        ),
        migrations.CreateModel(
            name='CarBookingRefund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refundAmount', models.FloatField()),
                ('refundStatus', models.CharField(max_length=255)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('cancellation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carbooking.carbookingcancellation')),
            ],
        ),
        migrations.CreateModel(
            name='CarBookingTicketDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pnrNumber', models.CharField(max_length=255)),
                ('invoiceNumber', models.CharField(max_length=255)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('bookingDetails', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carbooking.carbookingbookingdetails')),
            ],
        ),
        migrations.CreateModel(
            name='CarBookingTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txnid', models.CharField(max_length=255, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paymentStatus', models.CharField(choices=[('initiated', 'Initiated'), ('success', 'Success'), ('failed', 'Failed'), ('timeout', 'Timeout')], default='initiated', max_length=50)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('bookingDetails', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='carbooking.carbookingbookingdetails')),
            ],
        ),
        migrations.CreateModel(
            name='CarBookingVehicleDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicleCapacity', models.CharField(max_length=255)),
                ('tourDescription', models.TextField()),
                ('baseFare', models.FloatField()),
                ('GST', models.FloatField()),
                ('extraPerKM', models.FloatField()),
                ('extraPerHour', models.FloatField()),
                ('perNightCharge', models.FloatField()),
                ('status', models.BooleanField(default=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carbooking.carbookingpackage')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carbooking.carbookingvehicle')),
            ],
        ),
        migrations.AddField(
            model_name='carbookingbookingdetails',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='carbooking.carbookingvehicledetails'),
        ),
        migrations.CreateModel(
            name='CarBookingAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalSeats', models.IntegerField()),
                ('availableSeats', models.IntegerField()),
                ('availableDate', models.DateField()),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('vehicleDetails', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carbooking.carbookingvehicledetails')),
            ],
        ),
        migrations.CreateModel(
            name='CarBookingPaymentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mihpayid', models.CharField(blank=True, max_length=45, null=True)),
                ('mode', models.CharField(blank=True, max_length=45, null=True)),
                ('status', models.CharField(max_length=45)),
                ('unmappedstatus', models.CharField(blank=True, max_length=45, null=True)),
                ('txnid', models.CharField(max_length=45)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('addedon', models.DateTimeField(blank=True, null=True)),
                ('firstname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.TextField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('pincode', models.CharField(blank=True, max_length=20, null=True)),
                ('productinfo', models.CharField(max_length=255)),
                ('vehicle_name', models.CharField(blank=True, max_length=255, null=True)),
                ('package_name', models.CharField(blank=True, max_length=255, null=True)),
                ('journey_date', models.DateField(blank=True, null=True)),
                ('net_amount_debit', models.CharField(blank=True, max_length=45, null=True)),
                ('discount', models.CharField(blank=True, max_length=45, null=True)),
                ('bank_ref_num', models.CharField(blank=True, max_length=45, null=True)),
                ('bankcode', models.CharField(blank=True, max_length=45, null=True)),
                ('name_on_card', models.CharField(blank=True, max_length=45, null=True)),
                ('cardnum', models.CharField(blank=True, max_length=45, null=True)),
                ('error', models.CharField(blank=True, max_length=45, null=True)),
                ('error_message', models.CharField(blank=True, max_length=500, null=True)),
                ('payment_response', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='payment', to='carbooking.carbookingtransaction')),
            ],
            options={
                'db_table': 'carbooking_payment_details',
                'indexes': [models.Index(fields=['txnid'], name='carbooking__txnid_4e6973_idx'), models.Index(fields=['mihpayid'], name='carbooking__mihpayi_9867e3_idx'), models.Index(fields=['status'], name='carbooking__status_f11c84_idx'), models.Index(fields=['email'], name='carbooking__email_2f0d67_idx')],
            },
        ),
    ]
