# Generated by Django 5.2.12 on 2026-05-06 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carbooking', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carbookingbookingdetails',
            old_name='vehicle',
            new_name='vehicle_details',
        ),
    ]
