# Generated by Django 5.2.12 on 2026-04-17 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carbooking', '0002_alter_carbookingvehicle_vehicleimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='carbookingpackagecategory',
            name='categoryImage',
            field=models.ImageField(blank=True, null=True, upload_to='package_categories/%Y/%m/'),
        ),
    ]
