# Generated by Django 5.2.12 on 2026-04-23 08:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carbooking', '0003_carbookingpackagecategory_categoryimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='carbookingbookingdetails',
            name='pincode',
            field=models.CharField(default=0, max_length=15, validators=[django.core.validators.RegexValidator(message='Enter a valid 6-digit PIN code.', regex='^\\d{6}$')]),
            preserve_default=False,
        ),
    ]
