# Generated by Django 5.2.8 on 2026-01-13 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DTTDC_Captcha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('captcha_value', models.CharField(max_length=20)),
                ('captcha_token', models.CharField(max_length=100, unique=True)),
                ('attempts', models.PositiveIntegerField(default=3)),
                ('validate_status', models.CharField(choices=[('PENDING', 'Pending'), ('VALID', 'Valid'), ('INVALID', 'Invalid'), ('EXPIRED', 'Expired')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'dttdc_captcha',
            },
        ),
    ]
