# Generated by Django 5.2.8 on 2025-11-28 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dttdc_admin', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='dttdc_captcha',
            table='dttdc_captcha',
        ),
    ]
