# Generated by Django 5.2.9 on 2026-01-12 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dttdc_admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=40)),
                ('phone', models.CharField(max_length=20)),
                ('feedback_date', models.DateTimeField()),
                ('comment', models.CharField(max_length=2000)),
            ],
            options={
                'db_table': 'feedback',
                'ordering': ['-feedback_date'],
            },
        ),
    ]
