# Generated by Django 5.2.9 on 2026-01-12 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dttdc_admin', '0002_feedback'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
