# Generated by Django 5.2.8 on 2025-12-01 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dttdc_admin', '0002_alter_dttdc_captcha_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dttdc_captcha',
            name='attempts',
            field=models.PositiveIntegerField(default=3),
        ),
    ]
